// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import hactar "github.com/NodeFactoryIo/hactar-daemon/internal/hactar"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// DiskInfoService is an autogenerated mock type for the DiskInfoService type
type DiskInfoService struct {
	mock.Mock
}

// SendDiskInfo provides a mock function with given fields: diskInfo
func (_m *DiskInfoService) SendDiskInfo(diskInfo hactar.DiskInfo) (*http.Response, error) {
	ret := _m.Called(diskInfo)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(hactar.DiskInfo) *http.Response); ok {
		r0 = rf(diskInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hactar.DiskInfo) error); ok {
		r1 = rf(diskInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
