// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import hactar "github.com/NodeFactoryIo/hactar-daemon/internal/hactar"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MinerService is an autogenerated mock type for the MinerService type
type MinerService struct {
	mock.Mock
}

// SendMinerInfo provides a mock function with given fields: info
func (_m *MinerService) SendMinerInfo(info hactar.MinerInfo) (*http.Response, error) {
	ret := _m.Called(info)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(hactar.MinerInfo) *http.Response); ok {
		r0 = rf(info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hactar.MinerInfo) error); ok {
		r1 = rf(info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
