stats:
  interval: 50 #second
  blocks:
    interval: 10 #secon
jsonrpc:
  lotus-miner:
    url: "http://167.172.98.186:2345/rpc/v0"
    token: ""
  lotus-node:
    url: "http://167.172.98.186:1234/rpc/v0"
    token: ""
hactar:
  api-url: "http://127.0.0.1:3000/api"
log:
  level: "info"
