stats:
  interval: 60 #seconds
  blocks:
    interval: 50 #seconds
  uptime:
    interval: 10 #seconds
  balance:
    interval: 150 #seconds
jsonrpc:
  lotus-miner:
    url: "http://167.172.98.186:2345/rpc/v0"
    token: ""
  lotus-node:
    url: "http://167.172.98.186:1234/rpc/v0"
    token: ""
hactar:
  api-url: "http://127.0.0.1:3000/api"
log:
  level: "error"
