stats:
  interval: 60 #seconds
  blocks:
    interval: 50 #seconds
  uptime:
    interval: 10 #seconds
  balance:
    interval: 150 #seconds
jsonrpc:
  lotus-miner:
    url: "http://localhost:2345/rpc/v0"
    token: ""
  lotus-node:
    url: "http://localhost:1234/rpc/v0"
    token: ""
hactar:
  api-url: "https://api.hactar.app/api"
log:
  level: "error"
