// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserSession is an autogenerated mock type for the UserSession type
type UserSession struct {
	mock.Mock
}

// GetHactarToken provides a mock function with given fields:
func (_m *UserSession) GetHactarToken() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetLastCheckedHeight provides a mock function with given fields:
func (_m *UserSession) GetLastCheckedHeight() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// SaveSession provides a mock function with given fields:
func (_m *UserSession) SaveSession() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetHactarToken provides a mock function with given fields: token
func (_m *UserSession) SetHactarToken(token string) {
	_m.Called(token)
}

// SetLastCheckedHeight provides a mock function with given fields: height
func (_m *UserSession) SetLastCheckedHeight(height int64) {
	_m.Called(height)
}
