// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import lotus "github.com/NodeFactoryIo/hactar-daemon/internal/lotus"
import mock "github.com/stretchr/testify/mock"

// ClientService is an autogenerated mock type for the ClientService type
type ClientService struct {
	mock.Mock
}

// GetClientVersion provides a mock function with given fields:
func (_m *ClientService) GetClientVersion() (*lotus.ClientVersionResponse, error) {
	ret := _m.Called()

	var r0 *lotus.ClientVersionResponse
	if rf, ok := ret.Get(0).(func() *lotus.ClientVersionResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lotus.ClientVersionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
