// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import lotus "github.com/NodeFactoryIo/hactar-daemon/internal/lotus"
import mock "github.com/stretchr/testify/mock"

// PastDealsService is an autogenerated mock type for the PastDealsService type
type PastDealsService struct {
	mock.Mock
}

// GetAllPastDeals provides a mock function with given fields:
func (_m *PastDealsService) GetAllPastDeals() ([]lotus.PastDealResponse, error) {
	ret := _m.Called()

	var r0 []lotus.PastDealResponse
	if rf, ok := ret.Get(0).(func() []lotus.PastDealResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lotus.PastDealResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
