on: [pull_request, push]
name: Tests

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        shell: bash
        run: go test ./...
